export const ITEM_TEXT_OPTIONS = [
  'German Shephard',
  'Golder Retriever',
  'Saint Bernard',
  'French Bulldog',
  'Lakeland Terrier',
  'Siberian Husky',
  'Pomeranian',
  'Boston Terrier',
  'Yakutian Laika',
  'Beagle',
  'Dalmatian',
  'English Setter',
  'Belgian Sheepdog',
  'Chihuahua',
  'Poodle',
  'Greyhound',
  'Collie',
  'Bloodhound',
  'Chow Chow',
  'Rottweiler',
  'Labrador Retriever',
  'Scottish Deerhound',
  'Shetland Sheepdog',
  'Irish Setter',
  'Shiba Inu',
  'Great Dane',
  'Kinshu Ken',
  'Mastiff',
  'Shih Tzu',
  'Bernese Mountain Dog',
] as const;
