// currently used to reference the names of settings that are used by subcomponent specific settings but can be used to reference all
export enum SETTING_NAMES {
  LEFT = 'Left',
  TOP = 'Top',
  RIGHT = 'Right',
  BOTTOM = 'Bottom',
  WIDTH = 'Width',
  HEIGHT = 'Height',
  FADE = 'Fade',
  Y_OFFSET = 'Y-Offset',
  ENTRANCE = 'Entrance',
  EXIT = 'Exit',
  DISMISS = 'Dismiss',
  SIZE = 'Size',
  TYPE = 'Type',
  ALIGN = 'Align',
  ORDER = 'Order',
  COLOR = 'Color',
  BASIC_ICON = ' ',
  RADIUS = 'Radius',
  DIVIDER_WIDTH = 'Divider Width',
}
