export enum WORKSHOP_TOOLBAR_OPTION_BUTTON_NAMES {
  BORDER = 'Border',
  COLOR = 'Color',
  SHADOW = 'Shadow',
  SIZE = 'Size',
  PADDING = 'Padding',
  MARGIN = 'Margin',
  TEXT = 'Text',
  TEXT_FONT = 'Font',
  BACKGROUND = 'Background',
  POSITION = 'Position',
  BACKDROP = 'Backdrop',
  ANIMATIONS = 'Animations',
  ACTIONS = 'Actions',
  IMAGE = 'Image',
}
