export enum WORKSHOP_TOOLBAR_OPTION_BUTTON_NAMES {
  BORDER = 'Border',
  COLOR = 'Color',
  SHADOW = 'Shadow',
  SIZE = 'Size',
  PADDING = 'Padding',
  MARGIN = 'Margin',
  TEXT = 'Text',
  FONT = 'Font',
  DESIGN = 'Design',
  BACKGROUND = 'Background',
  ICON = 'Icon',
  POSITION = 'Position',
  TRANSITIONS = 'Transitions',
  BACKDROP = 'Backdrop',
}
