import { SUB_COMPONENT_PREVIEW_ELEMENT_IDS } from '../../../../../../consts/subcomponentPreviewElementIds.enum';
import { SUB_COMPONENTS } from '../../../../../../consts/subcomponentModes.enum';

type SubcomponentTypeToPreviewId = {
  [key in SUB_COMPONENTS]: SUB_COMPONENT_PREVIEW_ELEMENT_IDS;
}

export const subcomponentTypeToPreviewId: SubcomponentTypeToPreviewId = {
  [SUB_COMPONENTS.BASE]: SUB_COMPONENT_PREVIEW_ELEMENT_IDS.BASE,
  [SUB_COMPONENTS.CLOSE]: SUB_COMPONENT_PREVIEW_ELEMENT_IDS.CLOSE,
  [SUB_COMPONENTS.LAYER_1]: SUB_COMPONENT_PREVIEW_ELEMENT_IDS.LAYER_1,
  [SUB_COMPONENTS.LAYER_2]: SUB_COMPONENT_PREVIEW_ELEMENT_IDS.LAYER_2,
  [SUB_COMPONENTS.LAYER_3]: SUB_COMPONENT_PREVIEW_ELEMENT_IDS.LAYER_3,
};
